const mockedUsers = [
    {
        id: 1,
        name: "João",
        email: "joao@email.com",
        password: "senha123",
        type: "administrador",
    },
    {
        id: 2,
        name: "Rebeca",
        email: "rebeca@email.com",
        password: "senha456",
        type: "administrador",
    },
    {
        id: 3,
        name: "Diane",
        email: "diane@email.com",
        password: "senha789",
        type: "funcionário",
    },
    {
        id: 4,
        name: "Elisa",
        email: "elisa@email.com",
        password: "senha123",
        type: "funcionário",
    },
    {
        id: 5,
        name: "Nicholas",
        email: "nicholas@email.com",
        password: "senha789",
        type: "funcionário",
    },
    {
        id: 6,
        name: "Thiago",
        email: "thiago@email.com",
        password: "senha456",
        type: "administrador",
    },
    {
        id: 7,
        name: "Víctor",
        email: "victor@email.com",
        password: "senha123",
        type: "funcionário",
    },
    {
        id: 8,
        name: "Rita",
        email: "rita@email.com",
        password: "senha123",
        type: "administrador",
    },
    {
        id: 9,
        name: "Laura",
        email: "laura@email.com",
        password: "senha789",
        type: "funcionário",
    },
    {
        id: 10,
        name: "Fernando",
        email: "fernando@email.com",
        password: "senha456",
        type: "administrador",
    },
    {
        id: 11,
        name: "Caroline",
        email: "caroline@email.com",
        password: "senha123",
        type: "funcionário",
    },
    {
        id: 12,
        name: "Rafael",
        email: "rafael@email.com",
        password: "senha123",
        type: "administrador",
    },
    {
        id: 13,
        name: "Ana",
        email: "ana@email.com",
        password: "senha123",
        type: "administrador",
    },
    {
        id: 14,
        name: "Guilherme",
        email: "guilherme@email.com",
        password: "senha123",
        type: "administrador",
    },
    {
        id: 15,
        name: "Paulo",
        email: "paulo@email.com",
        password: "senha123",
        type: "administrador",
    },
];

export default mockedUsers;